version: 2.1
jobs:
 print_hello:
  docker:
   - image: circleci/node:13.8.0
  steps:
   - run: echo hello
 print_my_name:
  docker:
   - image: circleci/node:13.8.0
   steps:
    - run: echo myName


workflow:
 welcome:
  jobs:
   - print_hello
   - print_my_name: